disease_info = {
    "Apple_scab": " Fungal disease causing dark, scabby spots on leaves and fruit.",
    "Apple_black_rot": " Fungal infection producing black, sunken spots on fruit and brown leaf lesions.",
    "Apple_cedar_apple_rust": " Bright orange circular leaf spots caused by a fungus spread via cedar trees.",
    "Apple_healthy": " Leaf appears healthy with no disease symptoms.",
    "Background_without_leaves": " Image contains background material rather than plant leaves.",
    "Blueberry_healthy": " Healthy blueberry leaf with no visible disease symptoms.",
    "Cherry_powdery_mildew": " White, powdery fungal growth on leaf surfaces, reducing photosynthesis.",
    "Cherry_healthy": " Cherry leaf appears healthy and disease-free.",
    "Corn_gray_leaf_spot": " Narrow, rectangular grey lesions caused by Cercospora fungi.",
    "Corn_common_rust": " Red-brown raised pustules on both sides of the leaf due to rust fungus.",
    "Corn_northern_leaf_blight": " Long, cigar-shaped grey or tan lesions caused by fungal infection.",
    "Corn_healthy": " Corn leaf looks normal with no signs of disease.",
    "Grape_black_rot": " Brown circular leaf spots and mummified fruit caused by a fungal pathogen.",
    "Grape_black_measles": " Tiger-stripe leaf patterns and dark spotting on berries from trunk disease.",
    "Grape_leaf_blight": " Irregular dark spots that merge and cause leaf tissue death.",
    "Grape_healthy": " Grape leaf appears healthy and disease-free.",
    "Orange_haunglongbing": " Severe citrus disease causing yellow blotches and misshapen fruit (also 'citrus greening').",
    "Peach_bacterial_spot": "Dark, sunken spots on leaves and fruit caused by bacterial infection.",
    "Peach_healthy": " Healthy peach leaf with no visible lesions.",
    "Pepper_bacterial_spot": " Small water-soaked spots that turn brown or black, often with yellow halos.",
    "Pepper_healthy": " Bell pepper leaf appears healthy with no disease symptoms.",
    "Potato_early_blight": " Dark concentric-ring lesions ('bullseye pattern') on older leaves.",
    "Potato_late_blight": " Rapidly expanding brown patches; responsible for the historic potato famine.",
    "Potato_healthy": " Healthy potato leaf with uniform colour and no lesions.",
    "Raspberry_healthy": " Raspberry leaf appears healthy and undamaged.",
    "Soybean_healthy": " Healthy soybean leaf with no visible spots or discolouration.",
    "Squash_powdery_mildew": " White powder-like fungal growth causing leaf yellowing and reduced plant strength.",
    "Strawberry_leaf_scorch": "Purple-red spots merging into scorched-looking areas caused by fungal infection.",
    "Strawberry_healthy": "Healthy strawberry leaf with no visible disease symptoms.",
    "Tomato_bacterial_spot": " Small dark water-soaked spots that enlarge on tomato leaves and fruit.",
    "Tomato_early_blight": " Brown concentric-ring lesions starting on lower leaves.",
    "Tomato_late_blight": " Large dark water-soaked patches with pale borders; very fast spreading.",
    "Tomato_leaf_mold": " Yellow patches on top of leaves with olive-grey mould underneath.",
    "Tomato_septoria_leaf_spot": " Many tiny grey spots with dark borders, usually on older leaves.",
    "Tomato_spider_mites_two-spotted_spider_mite": " Pest damage causing pale stippling, bronzing, and webbing.",
    "Tomato_target_spot": " Circular brown lesions with target-like rings.",
    "Tomato_yellow_leaf_curl_virus": " Upward curling yellow leaves and stunted growth caused by a virus spread by whiteflies.",
    "Tomato_mosaic_virus": " Mottled light/dark green mosaic patterns and leaf deformation.",
    "Tomato_healthy": " Leaf appears healthy, with uniform colour and no obvious lesions.",
}
